[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_BUILD_IMAGE = "ubuntu-noble-24.04"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" 