redirects = [
  {from = "/hail-mario/", to = "/2014/06/01/hail-mario/", status = 301},
  {from = "/2014/06/01/hail-mary-o/", to = "/2014/06/01/hail-mario/", status = 301},
  {from = "/star-fox-64-design-mission-accomplished/", to = "/2013/04/20/star-fox-64-design-mission-accomplished/", status = 301},
  {from = "/e3-2013/", to = "/2013/06/15/e3-2013-genre-gender-breakdown/", status = 301},
  {from = "/save-developers-and-you-will-save-your-soul/", to = "/2014/03/13/save-developers-and-you-will-save-your-soul/", status = 301},
  {from = "/myst-tv-drama-and-companion-video-game/", to = "/2014/10/08/myst-tv-drama-and-companion-video-game/", status = 301},
  {from = "/old-school-hip-hop-is-the-new-golden-oldies/", to = "/2014/12/28/old-school-hip-hop-is-the-new-golden-oldies/", status = 301},
  {from = "/home-economics-2-0/", to = "/2015/01/27/home-economics-2-0/", status = 301},
  {from = "/gender/", to = "/2015/02/08/e3-2014-genre-gender-breakdown/", status = 301},
  {from = "/would-disney-buy-nintendo/", to = "/2015/05/07/would-disney-buy-nintendo/", status = 301},
  {from = "/buttons/", to = "/2015/05/31/buttons/", status = 301},
  {from = "/firewatch-review/", to = "/2016/02/21/firewatch-review/", status = 301},
  {from = "/the-witness-a-cheaters-review/", to = "/2016/03/11/the-witness-a-cheaters-review/", status = 301},
  {from = "/pokemon-goty/", to = "/2016/07/13/pokemon-goty/", status = 301},
  {from = "/nintendo-switch-presentation-2017-impressions/", to = "/2017/01/14/nintendo-switch-presentation-2017-impressions/", status = 301},
  {from = "/reggie-fils-aime-i-dont-mind-how-you-interact-with-our-ip-as-long-as-youre-interacting-with-it-every-day/", to = "/2017/01/15/reggie-fils-aime-i-dont-mind-how-you-interact-with-our-ip-as-long-as-youre-interacting-with-it-every-day/", status = 301},
  {from = "/the-second-console/", to = "/2017/02/10/the-second-console/", status = 301},
  {from = "/business/self-competing-and-time-blocking/", to = "/2017/04/23/self-competing-and-time-blocking/", status = 301},
  {from = "/self-competing-and-time-blocking/", to = "/2017/04/23/self-competing-and-time-blocking/", status = 301},
  {from = "/hail-mario-2-electrodrome-boogaloo/", to = "/2017/04/30/hail-mario-2-electrodrome-boogaloo/", status = 301},
  {from = "/general/sold-on-cross-network-play/", to = "/2017/06/18/sold-on-cross-network-play/", status = 301},
  {from = "/e3-2017/", to = "/2017/06/19/e3-2017/", status = 301},
  {from = "/sell-my-old-consoles-im-off-to-handheld/", to = "/2017/08/05/sell-my-old-consoles-im-off-to-handheld/", status = 301},
  {from = "/mario-rabbids-kingdom-battle-just-looking-around-is-a-joy/", to = "/2017/08/28/mario-rabbids-kingdom-battle-just-looking-around-is-a-joy/", status = 301},
  {from = "/super-mario-odyssey-a-review/", to = "/2017/11/19/super-mario-odyssey-a-review/", status = 301},
  {from = "/good-enough/", to = "/2017/11/22/good-enough/", status = 301},
  {from = "/big-ns-big-year/", to = "/2017/11/28/big-ns-big-year/", status = 301},
  {from = "/building-zero-counts/", to = "/2018/03/25/building-zero-counts/", status = 301},
  {from = "/cross-network-play-is-the-next-logical-step/", to = "/2018/03/25/cross-network-play-is-the-next-logical-step/", status = 301},
  {from = "/the-verge-my-xbox-one-s-is-now-a-meaningfully-different-console-to-my-ps4/", to = "/2018/04/22/the-verge-my-xbox-one-s-is-now-a-meaningfully-different-console-to-my-ps4/", status = 301},
  {from = "/microsofts-xbox-adaptive-controller/", to = "/2018/05/17/microsofts-xbox-adaptive-controller/", status = 301},
  {from = "/ps4-fortnite-accounts-are-blocked-on-the-nintendo-switch/", to = "/2018/06/12/ps4-fortnite-accounts-are-blocked-on-the-nintendo-switch/", status = 301},
  {from = "/sometimes-failure-leads-to-opportunity/", to = "/2018/06/12/sometimes-failure-leads-to-opportunity/", status = 301},
  {from = "/xbox-switch-better-together-campaign/", to = "/2018/06/22/xbox-switch-better-together-campaign/", status = 301},
  {from = "/cross-platform-play-coming-to-ps4-starting-with-fortnite/", to = "/2018/09/26/cross-platform-play-coming-to-ps4-starting-with-fortnite/", status = 301},
  {from = "/there-are-too-many-video-games-what-now/", to = "/2018/09/28/there-are-too-many-video-games-what-now/", status = 301},
  {from = "/demo-mode-rise-of-the-tomb-raider/", to = "/2016/01/18/demo-mode-rise-of-the-tomb-raider/", status = 301},
  {from = "/egoraptor-just-harshly-criticized-ocarina-of-time-on-the-internet/", to = "/2014/07/04/egoraptor-just-harshly-criticized-ocarina-of-time-on-the-internet/", status = 301}
]